# docker-compose.yml
version: "3.9"
services:
  api:
    container_name: app_dotnet
    build:
      context: ./dotnet
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    volumes:
      - ./dotnet/app_dotnet:/app/app_dotnet # sincroniza sua pasta local com a pasta /app dentro do container, então qualquer arquivo que você criar estará acessível do host e do container.
    networks:
      - monorepo-net
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Production

    working_dir: /app/app_dotnet
    command: ["dotnet", "run", "--no-launch-profile", "--urls", "http://0.0.0.0:5000"]

  web:
    container_name: app_angular
    build:
      context: ./angular
      dockerfile: Dockerfile.prod
    ports:
      - "4200:80" # Angular será servido via build otimizado (ng build)
    networks:
      - monorepo-net

networks:
  monorepo-net:
    driver: bridge
