FROM node:20

WORKDIR /app/app_angular/

# Copia package.json e package-lock.json para instalar dependências
COPY app_angular/package*.json ./

# Instala Angular CLI globalmente
RUN npm install -g @angular/cli

# Instala dependências do projeto
RUN npm install

# Copia o restante do código
COPY app_angular/. .

# Expõe a porta padrão do Angular
EXPOSE 4200

# Comando padrão para manter o container aberto com terminal bash
CMD ["bash"]
