# Dockerfile.dev
FROM node:20

WORKDIR /app/app_angular/

# Copia package.json e package-lock.json para instalar dependências primeiro
COPY app_angular/package*.json ./

# Instala Angular CLI globalmente
RUN npm install -g @angular/cli
RUN npm install

# Copia o restante do código
COPY app_angular/. .

EXPOSE 4200

# Comando para rodar Angular no modo dev e permitir conexões externas
CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200", "--poll=2000"]
